name: Setup marathon-cloud
description: Setup marathon-cloud in GitHub Actions
inputs:
  version:
    description: "The version of marathon-cloud to use. Defaults to the latest version."
    required: false
  skip-cache:
    description: 'Skip cache check? When set to "true", the action will always download the latest version.'
    required: false
    default: "false"
branding:
  color: green
runs:
  using: "node16"
  main: "lib/index.js"
